apiVersion: v1
kind: Service
metadata:
  name: "plantsdb-preloaded"
  namespace: "default"
spec:
  type: NodePort
  ports:
  - name: db2
    port: 50000
    protocol: "TCP"
    targetPort: 50000
  selector:
    app: "plantsdb-preloaded"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "plantsdb-preloaded"
  namespace: "default"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "plantsdb-preloaded"
    spec:
      containers:
      - name: plantsdb-preloaded-db2express-c
        image: mycluster.icp:8500/default/plantsdb-preloaded
        args: ["db2start"]
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INST1_PASSWORD
          value: "db2Pa2359w0rd123"
