apiVersion: v1
kind: Service
metadata:
  name: "plantsbyliberty"
  namespace: "default"
spec:
  type: NodePort
  ports:
  - name: http
    port: 9080
    protocol: "TCP"
    targetPort: 9080
  selector:
    app: "plantsbyliberty"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "plantsbyliberty"
  namespace: "default"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "plantsbyliberty"
    spec:
      containers:
      - name: plantsbyliberty
        image: mycluster.icp:8500/default/plantsbyliberty
